In [1]:
import numpy as np

In [4]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a1 = a.reshape(5,6)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
a2 = a1.ravel(order='F')
a2

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [7]:
for a3 in np.where(a2%6==1):
    print (a3)

[5 6 7 8 9]
